@startuml
'https://plantuml.com/class-diagram

class CreateWorkoutActivity {
}

class UpdateWorkoutActivity {
}

class GetWorkoutActivity {
}

class WorkoutModel {
 Date : date
 String : name
 String : notes
}

class ExerciseModel {
 String : name
}
@enduml